# Generated by LakehousePlumber
# Pipeline: acme_edw_event_log_monitoring
# FlowGroup: monitoring

from pyspark import pipelines as dp
from pyspark.sql import DataFrame

# Pipeline Configuration
PIPELINE_ID = "acme_edw_event_log_monitoring"
FLOWGROUP_ID = "monitoring"


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev._meta.error_events",
    comment="Materialized view: error_events",
    table_properties={},
)
def error_events():
    """Write to acme_edw_dev._meta.error_events from multiple sources"""
    # Materialized views use batch processing
    df = spark.sql(
        """SELECT * FROM all_pipelines_event_log WHERE event_type = 'error'"""
    )

    return df


@dp.materialized_view(
    name="acme_edw_dev._meta.pipeline_latency",
    comment="Materialized view: pipeline_latency",
    table_properties={},
)
def pipeline_latency():
    """Write to acme_edw_dev._meta.pipeline_latency from multiple sources"""
    # Materialized views use batch processing
    df = spark.sql(
        """SELECT _source_pipeline, avg(duration_ms) as avg_duration FROM all_pipelines_event_log GROUP BY _source_pipeline"""
    )

    return df
