# ──────────────────────────────────────────────────────────────────────────────
# Test Reporting Event Hook — acmi_edw_bronze
# Generated by Lakehouse Plumber — DO NOT EDIT
# ──────────────────────────────────────────────────────────────────────────────

from pyspark import pipelines as dp
from datetime import datetime, timezone

from test_reporting_providers.test_reporting_publisher import publish_results

# Mapping: unqualified table name → external test ID
_TEST_ID_MAP = {
    "tst_customer_pk_uniqueness": "SIT-G01",
    "tmp_test_tst_customer_completeness": "SIT-G02",
}

# Provider configuration (from config_file or empty dict)
_PROVIDER_CONFIG = {}

# Module-level state — safe because hooks run synchronously on the driver
_collected_results = []
_published = False

_TERMINAL_STATES = frozenset({"STOPPING", "FAILED", "CANCELED", "COMPLETED"})


@dp.on_event_hook(max_allowable_consecutive_failures=5)
def test_reporting_hook(event):
    """Accumulates DQ test results and publishes at pipeline terminal state."""
    global _published

    event_type = event.get("event_type", "unknown")

    # Collect DQ results from flow_progress events
    if event_type == "flow_progress":
        _handle_flow_progress(event)

    # Publish at terminal state
    if event_type == "update_progress":
        state = event.get("details", {}).get("update_progress", {}).get("state", "")
        if state in _TERMINAL_STATES and not _published:
            _published = True
            _publish_results(state, event)


def _handle_flow_progress(event):
    """Extract DQ expectation metrics from a flow_progress event."""
    details = event.get("details", {})
    flow_progress = details.get("flow_progress", {})
    data_quality = flow_progress.get("data_quality", {})
    expectations = data_quality.get("expectations", [])

    if not expectations:
        return

    # flow_name is in origin, fully qualified as catalog.schema.table
    origin = event.get("origin", {})
    raw_flow_name = origin.get("flow_name", "unknown")
    # Strip catalog.schema. prefix to get unqualified table name
    table_name = (
        raw_flow_name.rsplit(".", 1)[-1] if "." in raw_flow_name else raw_flow_name
    )

    # Only collect results for tables that have a test_id mapping
    if table_name not in _TEST_ID_MAP:
        return

    test_id = _TEST_ID_MAP[table_name]

    for exp in expectations:
        passed = exp.get("passed_records", 0)
        failed = exp.get("failed_records", 0)
        result = {
            "test_id": test_id,
            "flow_name": table_name,
            "expectation_name": exp.get("name", "unknown"),
            "passed_records": passed,
            "failed_records": failed,
            "status": "PASS" if failed == 0 else "FAIL",
            "collected_at": datetime.now(timezone.utc).isoformat(),
        }
        _collected_results.append(result)


def _publish_results(terminal_state, event):
    """Called once at pipeline termination. Publishes collected DQ results."""
    if not _collected_results:
        print("[LHP TestReporting] No DQ results collected — skipping publish.")
        return

    origin = event.get("origin", {})
    context = {
        "pipeline_id": origin.get("pipeline_id", ""),
        "update_id": origin.get("update_id", ""),
        "pipeline_name": "acmi_edw_bronze",
        "terminal_state": terminal_state,
    }

    try:
        from pyspark.sql import SparkSession

        spark = SparkSession.builder.getOrCreate()
        result = publish_results(
            results=list(_collected_results),
            config=dict(_PROVIDER_CONFIG),
            context=context,
            spark=spark,
        )
        published = result.get("published", 0) if isinstance(result, dict) else 0
        failed = result.get("failed", 0) if isinstance(result, dict) else 0
        print(
            f"[LHP TestReporting] Published {published} result(s), "
            f"{failed} failure(s) at state={terminal_state}."
        )
    except Exception as e:
        print(f"[LHP TestReporting] Publish failed: {e}")
