# Generated by LakehousePlumber
# Pipeline: acmi_edw_bronze
# FlowGroup: tst_customer_dq

from pyspark import pipelines as dp
from pyspark.sql.functions import *

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_bronze"
FLOWGROUP_ID = "tst_customer_dq"


# ============================================================================
# DATA QUALITY TESTS
# ============================================================================


@dp.expect_all({"no_duplicates": "duplicate_count == 0"})
@dp.table(name="tst_customer_pk_uniqueness", comment="Test: uniqueness", temporary=True)
def tst_customer_pk_uniqueness():
    """Test: uniqueness"""
    return spark.sql("""
        SELECT customer_id, COUNT(*) as duplicate_count
                    FROM v_customer_bronze_DQE
                    GROUP BY customer_id
                    HAVING COUNT(*) > 1
    """)


@dp.expect_all(
    {
        "required_fields_complete": "customer_id IS NOT NULL AND name IS NOT NULL AND nation_id IS NOT NULL"
    }
)
@dp.table(
    name="tmp_test_tst_customer_completeness",
    comment="Test: completeness",
    temporary=True,
)
def tmp_test_tst_customer_completeness():
    """Test: completeness"""
    return spark.sql("""
        SELECT customer_id, name, nation_id
                    FROM v_customer_bronze_DQE
    """)


@dp.expect_all(
    {"value_in_range": "account_balance >= '-1000' AND account_balance <= '10000'"}
)
@dp.table(
    name="tmp_test_tst_customer_balance_range", comment="Test: range", temporary=True
)
def tmp_test_tst_customer_balance_range():
    """Test: range"""
    return spark.sql("""
        SELECT account_balance
                    FROM v_customer_bronze_DQE
    """)
