# Generated by LakehousePlumber
# Pipeline: acme_edw_event_log_monitoring
# FlowGroup: monitoring

from pyspark import pipelines as dp
from pyspark.sql import DataFrame

# Pipeline Configuration
PIPELINE_ID = "acme_edw_event_log_monitoring"
FLOWGROUP_ID = "monitoring"


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev._meta.custom_analysis",
    comment="Materialized view: custom_analysis",
    table_properties={},
)
def custom_analysis():
    """Write to acme_edw_dev._meta.custom_analysis from multiple sources"""
    # Materialized views use batch processing
    df = spark.sql("""SELECT
  _source_pipeline,
  event_type,
  date_trunc('DAY', timestamp) AS event_day,
  count(*) AS daily_event_count
FROM all_pipelines_event_log
WHERE event_type IN ('FLOW_PROGRESS', 'DATASET_CREATED')
GROUP BY _source_pipeline, event_type, date_trunc('DAY', timestamp)""")

    return df
