# Databricks notebook source
# Generated by Lakehouse Plumber — Monitoring Event Log Union
# This notebook runs N independent streaming queries (one per pipeline event log)
# into a single Delta table. Each stream has its own checkpoint directory,
# so adding or removing pipelines does not invalidate existing checkpoints.

from concurrent.futures import ThreadPoolExecutor, as_completed

from pyspark.sql import functions as F

# ---------------------------------------------------------------------------
# Configuration (injected at generation time)
# ---------------------------------------------------------------------------
TARGET_TABLE = "acme_edw_dev._meta.all_pipelines_event_log"
CHECKPOINT_BASE = "/Volumes/acme_edw_dev/_meta/checkpoints/event_logs"
MAX_WORKERS = 10

SOURCES = [
    ("acmi_edw_bronze", "acme_edw_dev._meta.acmi_edw_bronze_event_log"),
    ("acmi_edw_modelled", "acme_edw_dev._meta.acmi_edw_modelled_event_log"),
    ("acmi_edw_raw", "acme_edw_dev._meta.acmi_edw_raw_event_log"),
    ("acmi_edw_silver", "acme_edw_dev._meta.acmi_edw_silver_event_log"),
    ("custom_datasource", "acme_edw_dev._meta.custom_datasource_event_log"),
    ("gold_load", "acme_edw_dev._meta.gold_load_event_log"),
    ("kafka_sample_pipeline", "acme_edw_dev._meta.kafka_sample_pipeline_event_log"),
    ("namespace_validation", "acme_edw_dev._meta.namespace_validation_event_log"),
    ("sample_python_func_pipeline", "acme_edw_dev._meta.sample_python_func_pipeline_event_log"),
]


# ---------------------------------------------------------------------------
# Worker function — one independent streaming query per source
# ---------------------------------------------------------------------------
def process_source(pipeline_name: str, table_ref: str) -> str:
    """Run a single streaming query from table_ref into TARGET_TABLE.

    Each query gets its own checkpoint under CHECKPOINT_BASE/{pipeline_name}.
    Uses trigger(availableNow=True) so the query processes all available data
    and then terminates.
    """
    checkpoint = f"{CHECKPOINT_BASE}/{pipeline_name}"
    query = None
    try:
        query = (
            spark.readStream  # noqa: F821 — spark is provided by Databricks runtime
            .format("delta")
            .table(table_ref)
            .withColumn("_source_pipeline", F.lit(pipeline_name))
            .writeStream.format("delta")
            .outputMode("append")
            .option("checkpointLocation", checkpoint)
            .option("mergeSchema", "true")
            .trigger(availableNow=True)
            .toTable(TARGET_TABLE)
        )
        query.awaitTermination()
    except Exception:
        if query is not None:
            try:
                query.stop()
            except Exception:
                pass
        raise
    return pipeline_name


# ---------------------------------------------------------------------------
# Main execution — parallel streams with error collection
# ---------------------------------------------------------------------------
successes = []
failures = []

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = {
        executor.submit(process_source, name, ref): name
        for name, ref in SOURCES
    }
    for future in as_completed(futures):
        pipeline_name = futures[future]
        try:
            future.result()
            successes.append(pipeline_name)
        except Exception as exc:
            failures.append((pipeline_name, str(exc)))

# Report results
summary_parts = [f"Processed {len(successes)}/{len(SOURCES)} event log streams."]
if successes:
    summary_parts.append(f"Succeeded: {', '.join(sorted(successes))}")
if failures:
    failure_details = "; ".join(
        f"{name}: {err}" for name, err in sorted(failures)
    )
    summary_parts.append(f"Failed: {failure_details}")

summary = " | ".join(summary_parts)

if failures:
    raise RuntimeError(
        f"Event log union failed for {len(failures)} pipeline(s): {summary}"
    )

dbutils.notebook.exit(summary)  # noqa: F821 — dbutils provided by Databricks runtime
