# Generated by LakehousePlumber
# Pipeline: acme_edw_event_log_monitoring
# FlowGroup: monitoring

from jobs_stats_loader import get_jobs_stats
from pyspark import pipelines as dp
from pyspark.sql import DataFrame

# Pipeline Configuration
PIPELINE_ID = "acme_edw_event_log_monitoring"
FLOWGROUP_ID = "monitoring"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_jobs_stats():
    """Python source: load_jobs_stats"""
    # Call the external Python function with spark and parameters
    parameters = {}
    df = get_jobs_stats(spark, parameters)

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev._meta.jobs_stats",
    comment="Materialized view: jobs_stats",
    table_properties={},
)
def jobs_stats():
    """Write to acme_edw_dev._meta.jobs_stats from multiple sources"""
    # Materialized views use batch processing
    df = spark.sql("""SELECT * FROM v_jobs_stats""")

    return df


@dp.materialized_view(
    name="acme_edw_dev._meta.events_summary",
    comment="Materialized view: events_summary",
    table_properties={},
)
def events_summary():
    """Write to acme_edw_dev._meta.events_summary from multiple sources"""
    # Materialized views use batch processing
    df = spark.sql("""WITH run_info AS (
    SELECT
        origin.pipeline_name,
        origin.pipeline_id,
        origin.update_id,
        MIN(`timestamp`) AS run_start_time,
        MAX(`timestamp`) AS run_end_time,
        MAX_BY(
            CASE WHEN event_type = 'update_progress'
                THEN details:update_progress:state::STRING END,
            CASE WHEN event_type = 'update_progress'
                THEN `timestamp` END
        ) AS run_status
    FROM acme_edw_dev._meta.all_pipelines_event_log
    GROUP BY origin.pipeline_name, origin.pipeline_id, origin.update_id
),
run_metrics AS (
    SELECT
        origin.pipeline_name,
        origin.update_id,
        SUM(COALESCE(details:flow_progress:metrics:num_upserted_rows::BIGINT, 0))
          AS total_upserted_rows,
        SUM(COALESCE(details:flow_progress:metrics:num_deleted_rows::BIGINT, 0))
          AS total_deleted_rows,
        SUM(COALESCE(details:flow_progress:data_quality:dropped_records::BIGINT, 0))
          AS total_dropped_records,
        COUNT(DISTINCT origin.flow_name) AS tables_processed
    FROM acme_edw_dev._meta.all_pipelines_event_log
    WHERE event_type = 'flow_progress'
      AND details:flow_progress:metrics IS NOT NULL
    GROUP BY origin.pipeline_name, origin.update_id
),
run_config AS (
    SELECT
        origin.pipeline_name,
        origin.update_id,
        MAX(details:create_update:runtime_version:dbr_version::STRING) AS dbr_version,
        MAX(CASE WHEN details:create_update:config:serverless::BOOLEAN
            THEN 'Serverless' ELSE 'Classic' END) AS compute_type,
        MAX(details:create_update:cause::STRING) AS trigger_cause,
        MAX(details:create_update:full_refresh::BOOLEAN) AS is_full_refresh
    FROM acme_edw_dev._meta.all_pipelines_event_log
    WHERE event_type = 'create_update'
    GROUP BY origin.pipeline_name, origin.update_id
)
SELECT
    ri.pipeline_name,
    ri.pipeline_id,
    ri.update_id,
    ri.run_status,
    rc.trigger_cause,
    rc.is_full_refresh,
    rc.dbr_version,
    rc.compute_type,
    ri.run_start_time,
    ri.run_end_time,
    ROUND((unix_timestamp(ri.run_end_time) - unix_timestamp(ri.run_start_time)) / 60, 2)
      AS duration_minutes,
    COALESCE(rm.tables_processed, 0) AS tables_processed,
    COALESCE(rm.total_upserted_rows, 0) AS total_upserted_rows,
    COALESCE(rm.total_deleted_rows, 0) AS total_deleted_rows,
    COALESCE(rm.total_upserted_rows, 0) + COALESCE(rm.total_deleted_rows, 0)
      AS total_rows_affected,
    COALESCE(rm.total_dropped_records, 0) AS total_dropped_records
FROM run_info ri
LEFT JOIN run_metrics rm
  ON ri.pipeline_name = rm.pipeline_name AND ri.update_id = rm.update_id
LEFT JOIN run_config rc
  ON ri.pipeline_name = rc.pipeline_name AND ri.update_id = rc.update_id
ORDER BY ri.run_start_time DESC""")

    return df
